//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViviPlusTT.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Format
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Format()
        {
            this.Response = new HashSet<Response>();
        }
    
        public int Id { get; set; }
        public int ConvertId { get; set; }
        public string Name { get; set; }
        public string IOClassName { get; set; }
        public string Currency { get; set; }
        public string InputPath { get; set; }
        public string OutputPath { get; set; }
        public bool IsActive { get; set; }
        public int IbsFormatId { get; set; }
        public string InputPattern { get; set; }
        public string OutputPattern { get; set; }
    
        public virtual Convertion Convertion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Response { get; set; }
    }
}
