//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViviPlusTT.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Response()
        {
            this.ResponseData = new HashSet<ResponseData>();
        }
    
        public int Id { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public string Status { get; set; }
        public int FormatId { get; set; }
        public string FileName { get; set; }
        public short Records { get; set; }
        public decimal Total { get; set; }
        public decimal TotalConverted { get; set; }
        public string RegisteredBy { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string XMLGenerated { get; set; }
        public Nullable<int> BankImportId { get; set; }
        public string AuditLog { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Format Format { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseData> ResponseData { get; set; }
    }
}
