//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViviPlusTT.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViviPlusTTEntities : DbContext
    {
        public ViviPlusTTEntities()
            : base("name=ViviPlusTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Convertion> Convertion { get; set; }
        public virtual DbSet<Format> Format { get; set; }
        public virtual DbSet<Response> Response { get; set; }
        public virtual DbSet<ResponseData> ResponseData { get; set; }
    }
}
